import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import { ToastContainer } from "react-toastify";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <script
        async
        src='https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2825016877369969'
        crossorigin='anonymous'
      ></script>
      <script
        async
        src='https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2825016877369969'
        crossorigin='anonymous'
      ></script>
      <meta
        name='google-adsense-account'
        content='ca-pub-2825016877369969'
      ></meta>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <Header></Header>
        </div>
        <div className='h-full'>{children}</div>
        <ToastContainer />
      </body>
    </html>
  );
}
